---
language: ruby
services:
  - docker
rvm:
  - 2.3.6
  - 2.4.0
  - 2.4.1
  - 2.4.3
  - 2.5.0
install:
  - gem install bundler:1.17.2
  - bundle install
script:
  - bundle exec rake spec
  - echo $DOCKERHUB_TOKEN | docker login -u residentadvisor --password-stdin
  - docker build -t residentadvisor/spotify-token-swap-service:1.0.0 .
  - docker push residentadvisor/spotify-token-swap-service:1.0.0
